language: python
python:
  - "pypy"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
# Test both current major versions of Inkscape
env:
  - INKSCAPE_VERSION="0.48.3.1-1ubuntu1.1"
  - INKSCAPE_VERSION="0.91.0+37~ubuntu12.04.1"
# Start xvfb so we can run Inkscape headless
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install:
  - sudo add-apt-repository -y ppa:inkscape.dev/stable
  - sudo apt-get update -qq
  - sudo apt-get install -qq "inkscape=$INKSCAPE_VERSION"
  - pip install -r test-requirements.txt
# command to run tests
script: nosetests --with-coverage --cover-branches
after_success: coveralls
